const rotors = {
  I: 'EKMFLGDQVZNTOWYHXUSPAIBRCJ',
  II: 'AJDKSIRUXBLHWTMCQGZNPYFVOE',
  III: 'BDFHJLCPRTXVZNYEIWGAKMUSQO',
  IV: 'ESOVPZJAYQUIRHXLNFTGKDCMWB',
  V: 'VZBRGITYUPSDNHLXAWMJQOFECK',
  VI: 'JPGVOUMFYQBENHZRDKASXLICTW',
  VII: 'NZJHGRCXMYSWBOUFAIVLPEKQDT',
  VIII: 'FKQHTLXOCBJSPDZRAMEWNIUYGV',
}
